### ISSUE TITLE
Icons are invisible

### ISSUE THREAD

**Issue by gideonyong** [xMrVizzy/button-toolbar#2]
Icons seem to be invisible but i can click on them and toggle lights 

I wonder if this is related:
https://github.com/home-assistant/frontend/issues/5905

```
                  - type: custom:button-toolbar
                    #aspect_ratio: 1/2
                    content:
                      entity: light.leviton_living_room
                      image: /local/pictures/lightbulb.png
                      #height: 60%
                    toolbar:
                      - type: service
                        name: Toggle
                        icon: mdi:lightbulb
                        service:
                          name: light.toggle
                          entity: light.leviton_living_room 
```
